name: Deploy To Mirror | 部署到镜像站点

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: github.repository == 'misitebao/wails-docsv2'

    steps:
      - name: Checkout | 切换分支
        uses: actions/checkout@master
        with:
          ref: master

      - name: Setup Hugo | 设置Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.76"
          extended: true

      - name: Build | 构建
        run: hugo --minify

      - name: Deploy to Server | 部署到服务器
        uses: hengkx/ssh-deploy@v1.0.1
        with:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_HOST_USER }} # 为了用户信息安全对敏感数据可以在secrets中配置请看下图
          PASSWORD: ${{ secrets.DEPLOY_HOST_PASSWORD }}
          SOURCE: "public"
          TARGET: "/www/wwwroot/v2.wails.top"
